routes/web.php
<?php

Route::get('/', 'WelcomeController@index')->name('index');
Route::get('/aboutUs', 'WelcomeController@abouts')->name('about');
Route::get('{id?}-and-pricing', 'WelcomeController@service')->name('service');
Route::get('/our-Work', 'WelcomeController@ourworks')->name('our.work');
Route::get('/web/school', 'WelcomeController@school')->name('school.lesson');
Route::get('/lesson-register/{data?}', 'WelcomeController@lessonregister')->name('lesson.register');
Route::post('/register/lesson', 'Lesson_registration_Controller@store')->name('lessonRegister.store');
Route::get('web/lesson', 'WelcomeController@lesson')->name('lesson');
Route::get('special/{data}', 'WelcomeController@special')->name('special');
Route::get('show-{lesson}', 'WelcomeController@lessonshow')->name('lesson.show');

Route::get('/blog/news', 'Blog_Controller@blogitems')->name('blognews');
Route::get('/blog/{id}', 'Blog_Controller@blogid')->name('blogid');
Route::post('/blog/created', 'Blog_Controller@create')->name('blog.created');
Route::get('/contact', 'WelcomeController@contact')->name('contact');
Route::post('/send', 'WelcomeController@send')->name('send');
Route::post('/package', 'WelcomeController@packages')->name('package');
Auth::routes(['register' => false]);
Route::redirect('/home', '/admin');



Route::group([ 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::resource('campetition', 'CampetitionController');
    Route::get('ajaxRequest/{id}', 'CampetitionController@ajaxRequest');
    Route::get('result', 'CampetitionController@result')->name('results');
    Route::get('trashCache', 'CampetitionController@trashCache')->name('trashCache');

});
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/contact', 'ContactController');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');
    Route::resource('slider', 'SliderController');
    Route::resource('about', 'AboutParentController');
    Route::resource('aboutinform', 'AboutInformController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');
    Route::resource('blog', 'BlogController');
    Route::get('blog/chek/slug', 'BlogController@chek')->name('chek.slug');
    Route::resource('service', 'ServiceController');
    Route::resource('service', 'ServiceController');
    Route::get('service/view/{id}', 'ServiceInformateController@view')->name('service_info.view');
    Route::get('service/add/{id}', 'ServiceInformateController@create')->name('service_info.created');
    Route::resource('service_info', 'ServiceInformateController');
    Route::resource('service_Package', 'ServicePackage');
    Route::get('service/Package/{id}', 'ServicePackage@creates')->name('ChildservicesPackage');
    Route::resource('bcomments', 'BlogCommentsController');
    Route::post('bcomments/delete', 'BlogCommentsController@delete')->name('comment.delete');


//    Lesson start


        Route::resource('lesson', 'Lesson\LessonController');
        Route::resource('trainers', 'Lesson\LessonTrainersController');
        Route::resource('lessonPrice', 'Lesson\LessonPriceController');
        Route::resource('special', 'Lesson\LessonSpecialModels');
        Route::resource('specialInform', 'Lesson\LessonSpecialInformateModels');
        Route::get('specialInforms/{data}', 'Lesson\LessonSpecialInformateModels@create')->name('create.special');
        Route::get('packageLesson', 'RegisterPackageController@lesson')->name('package.Lesson');
        Route::get('packageLessons/{id}', 'RegisterPackageController@lessonUpdate')->name('package.Lessons');

        Route::get('packageService', 'RegisterPackageController@service')->name('package.Service');
        Route::get('packageService/{id}', 'RegisterPackageController@serviceUpdate')->name('package.Services');







});

app/Models/Lesson/LessonInformateModels.php
<?php

namespace App\Models\Lesson;

use Illuminate\Database\Eloquent\Model;

class LessonInformateModels extends Model
{
    protected $fillable = [
        'parent_id',
        'title',

        'description',

    ];
}

app/Models/Lesson/LessonModels.php
<?php

namespace App\Models\Lesson;

use Illuminate\Database\Eloquent\Model;

class LessonModels extends Model
{
    protected $fillable = [
        'slug',
        'title',
        'language',
        'description',
        'avatar',
        'status',
        'time',
        'math',
        'onlinePersonal',
        'onlineGroup',
        'offlinePersonal',
        'offlineGroup',
    ];
}

app/Models/Lesson/LessonParentModels.php
<?php

namespace App\Models\Lesson;

use Illuminate\Database\Eloquent\Model;

class LessonParentModels extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'data',
        'description',
        'avatar',
        'logo',
        'price_id',
        'slogan',
    ];
}

app/Models/Lesson/LessonPriceListModels.php
<?php

namespace App\Models\Lesson;

use Illuminate\Database\Eloquent\Model;

class LessonPriceListModels extends Model
{
    protected $fillable = [
        'math',
        'time',
        'onlinePersonal',
        'onlineGroup',
        'offlinePersonal',
        'offlineGroup',
    ];
}

app/Models/Lesson/LessonTrainersIdGroupsModels.php
<?php

namespace App\Models\Lesson;

use Illuminate\Database\Eloquent\Model;

class LessonTrainersIdGroupsModels extends Model
{
    protected $fillable = [
        'lesson_id',
        'trainers_id',

    ];
}

app/Models/Lesson/LessonTrainersModels.php
<?php

namespace App\Models\Lesson;

use Illuminate\Database\Eloquent\Model;

class LessonTrainersModels extends Model
{
    protected $fillable = [
        'name',
        'profession',
        'avatar',
    ];
}

app/Models/Lesson/RegisterLessonModel.php
<?php

namespace App\Models\Lesson;

use Illuminate\Database\Eloquent\Model;

class RegisterLessonModel extends Model
{
    protected $fillable = [
        'name',
        'age',
        'email',
        'tel',
        'slug',
        'status',

    ];
}

app/Http/Controllers/Admin/Lesson/LessonController.php
<?php

namespace App\Http\Controllers\Admin\Lesson;

use App\Models\Lesson\LessonModels;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lesson=LessonModels::get();

        return view('admin.Lesson.lesson.index',compact('lesson'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.Lesson.lesson.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->has('avatar')) {

            $imagename = date("Y") . '/' . date("m") . '/' . rand(1, 99999) . '.' . $request->avatar->getClientOriginalExtension();

            $destinationPath = public_path('lesson/');
            $pah = public_path('lesson/' . date("Y") . '/' . date("m"));
            if (!file_exists($pah) > 0):
                if (!is_dir($pah . date("Y") . '/' . date("m"))) {
                    mkdir($pah, 0755, true);
                }endif;

            $thumb_img = Image::make($request->avatar->getRealPath())->encode('jpg', 75);
            $thumb_img->save($destinationPath . '/' . $imagename, 80);

            LessonModels::create([

                'slug'=>$request['slug'],
                'title'=>$request['title'],
                'language'=>$request['language'],
                'description'=>$request['description'],
                'status'=>$request['status'],
                'time'=>$request['time'],
                'math'=>$request['math'],
                'onlinePersonal'=>$request['onlinePersonal'],
                'onlineGroup'=>$request['onlineGroup'],
                'offlinePersonal'=>$request['offlinePersonal'],
                'offlineGroup'=>$request['offlineGroup'],
                'avatar'=>'lesson/'.$imagename,
            ]);

            return redirect()->route('admin.lesson.index');
        }else{

            return back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lesson=LessonModels::find($id);

        return view('admin.Lesson.lesson.edit',compact('lesson','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->has('avatar')) {

            $imagename = date("Y") . '/' . date("m") . '/' . rand(1, 99999) . '.' . $request->avatar->getClientOriginalExtension();

            $destinationPath = public_path('lesson/');
            $pah = public_path('lesson/' . date("Y") . '/' . date("m"));
            if (!file_exists($pah) > 0):
                if (!is_dir($pah . date("Y") . '/' . date("m"))) {
                    mkdir($pah, 0755, true);
                }endif;

            $thumb_img = Image::make($request->avatar->getRealPath())->encode('jpg', 75);
            $thumb_img->save($destinationPath . '/' . $imagename, 80);

            LessonModels::find($id)->update([
                'slug'=>$request['slug'],
                'title'=>$request['title'],
                'language'=>$request['language'],
                'description'=>$request['description'],
                'status'=>$request['status'],
                'time'=>$request['time'],
                'math'=>$request['math'],
                'onlinePersonal'=>$request['onlinePersonal'],
                'onlineGroup'=>$request['onlineGroup'],
                'offlinePersonal'=>$request['offlinePersonal'],
                'offlineGroup'=>$request['offlineGroup'],
                'avatar'=>'lesson/'.$imagename,
            ]);

            return redirect()->route('admin.lesson.index');
        }else{
            LessonModels::find($id)->update([
                'slug'=>$request['slug'],
                'title'=>$request['title'],
                'language'=>$request['language'],
                'description'=>$request['description'],
                'status'=>$request['status'],
                'time'=>$request['time'],
                'math'=>$request['math'],
                'onlinePersonal'=>$request['onlinePersonal'],
                'onlineGroup'=>$request['onlineGroup'],
                'offlinePersonal'=>$request['offlinePersonal'],
                'offlineGroup'=>$request['offlineGroup'],

            ]);
            return redirect()->route('admin.lesson.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lesson=LessonModels::find($id)->delete();
        return  back();

    }
}

app/Http/Controllers/Admin/Lesson/LessonPriceController.php
<?php

namespace App\Http\Controllers\Admin\Lesson;

use App\Models\Lesson\LessonPriceListModels;
use App\Models\Lesson\LessonTrainersModels;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LessonPriceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lessonPrice=LessonPriceListModels::get();

        return view('admin.Lesson.lessonPrice.index',compact('lessonPrice'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.Lesson.lessonPrice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        LessonPriceListModels::create($request->all());
        return redirect()->route('admin.lessonPrice.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lessonPrice=LessonPriceListModels::find($id);

        return view('admin.Lesson.lessonPrice.edit',compact('lessonPrice','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $lessonPrice=LessonPriceListModels::find($id)->update($request->all());
        return redirect()->route('admin.lessonPrice.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lessonPrice=LessonPriceListModels::find($id)->delete();
        return  back();
    }
}

app/Http/Controllers/Admin/Lesson/LessonSpecialInformateModels.php
<?php

namespace App\Http\Controllers\Admin\Lesson;

use App\Models\Lesson\LessonInformateModels;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LessonSpecialInformateModels extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        return view('admin.Lesson.special.info.create',compact('id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $specialInform=LessonInformateModels::create($request->all());

        return redirect()->route('admin.specialInform.show',$request->parent_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {


        $specialInform=LessonInformateModels::where('parent_id',$id)->get();

        return view('admin.Lesson.special.info.index',compact('id','specialInform'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $specialInform=LessonInformateModels::find($id);

        return view('admin.Lesson.special.info.edit',compact('id','specialInform'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $specialInform=LessonInformateModels::find($id)->update($request->all());
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $specialInform=LessonInformateModels::find($id)->delete();
        return back();
    }
}

resources/views/admin/Lesson/lessonPrice/create.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">


        <div class="card-body">
            <form action="{{ route("admin.lessonPrice.store") }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group {{ $errors->has('time') ? 'has-error' : '' }}">
                    <label for="time">րոպե</label>
                    <input type="text" id="time" name="time" class="form-control" value="" required>
                    @if($errors->has('time'))
                        <em class="invalid-feedback">
                            {{ $errors->first('time') }}
                        </em>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('math') ? 'has-error' : '' }}">
                    <label for="math">Ամիս</label>
                    <input type="text" id="math" name="math" class="form-control" value="" required>
                    @if($errors->has('math'))
                        <em class="invalid-feedback">
                            {{ $errors->first('math') }}
                        </em>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('onlinePersonal') ? 'has-error' : '' }}">
                    <label for="onlinePersonal">Online Անհատական</label>
                    <input type="text" id="onlinePersonal" name="onlinePersonal" class="form-control" value="" required>
                    @if($errors->has('onlinePersonal'))
                        <em class="invalid-feedback">
                            {{ $errors->first('onlinePersonal') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('onlineGroup') ? 'has-error' : '' }}">
                    <label for="onlineGroup">Online Խմբակային</label>
                    <input type="text" id="onlineGroup" name="onlineGroup" class="form-control" value="" required>
                    @if($errors->has('onlineGroup'))
                        <em class="invalid-feedback">
                            {{ $errors->first('onlineGroup') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('offlinePersonal') ? 'has-error' : '' }}">
                    <label for="offlinePersonal">offline Անհատական</label>
                    <input type="text" id="offlinePersonal" name="offlinePersonal" class="form-control" value="" required>
                    @if($errors->has('offlinePersonal'))
                        <em class="invalid-feedback">
                            {{ $errors->first('offlinePersonal') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('offlineGroup') ? 'has-error' : '' }}">
                    <label for="offlineGroup">offline Խմբակային</label>
                    <input type="text" id="offlineGroup" name="offlineGroup" class="form-control" value="" required>
                    @if($errors->has('offlineGroup'))
                        <em class="invalid-feedback">
                            {{ $errors->first('offlineGroup') }}
                        </em>
                    @endif
                </div>






                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/Lesson/lessonPrice/edit.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">


        <div class="card-body">
            <form action="{{ route("admin.lessonPrice.update",$id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="form-group {{ $errors->has('time') ? 'has-error' : '' }}">
                    <label for="time">րոպե</label>
                    <input type="text" id="time" name="time" class="form-control" value="{{ old('time', isset($lessonPrice) ? $lessonPrice->time : '') }}" required>
                    @if($errors->has('time'))
                        <em class="invalid-feedback">
                            {{ $errors->first('time') }}
                        </em>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('math') ? 'has-error' : '' }}">
                    <label for="math">Ամիս</label>
                    <input type="text" id="math" name="math" class="form-control" value="{{ old('math', isset($lessonPrice) ? $lessonPrice->math : '') }}" required>
                    @if($errors->has('math'))
                        <em class="invalid-feedback">
                            {{ $errors->first('math') }}
                        </em>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('onlinePersonal') ? 'has-error' : '' }}">
                    <label for="onlinePersonal">Online Անհատական</label>
                    <input type="text" id="onlinePersonal" name="onlinePersonal" class="form-control" value="{{ old('onlinePersonal', isset($lessonPrice) ? $lessonPrice->onlinePersonal : '') }}" required>
                    @if($errors->has('onlinePersonal'))
                        <em class="invalid-feedback">
                            {{ $errors->first('onlinePersonal') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('onlineGroup') ? 'has-error' : '' }}">
                    <label for="onlineGroup">Online Խմբակային</label>
                    <input type="text" id="onlineGroup" name="onlineGroup" class="form-control" value="{{ old('onlineGroup', isset($lessonPrice) ? $lessonPrice->onlineGroup : '') }}" required>
                    @if($errors->has('onlineGroup'))
                        <em class="invalid-feedback">
                            {{ $errors->first('onlineGroup') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('offlinePersonal') ? 'has-error' : '' }}">
                    <label for="offlinePersonal">offline Անհատական</label>
                    <input type="text" id="offlinePersonal" name="offlinePersonal" class="form-control" value="{{ old('offlinePersonal', isset($lessonPrice) ? $lessonPrice->offlinePersonal : '') }}" required>
                    @if($errors->has('offlinePersonal'))
                        <em class="invalid-feedback">
                            {{ $errors->first('offlinePersonal') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('offlineGroup') ? 'has-error' : '' }}">
                    <label for="offlineGroup">offline Խմբակային</label>
                    <input type="text" id="offlineGroup" name="offlineGroup" class="form-control" value="{{ old('offlineGroup', isset($lessonPrice) ? $lessonPrice->offlineGroup : '') }}" required>
                    @if($errors->has('offlineGroup'))
                        <em class="invalid-feedback">
                            {{ $errors->first('offlineGroup') }}
                        </em>
                    @endif
                </div>
                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/Lesson/lessonPrice/index.blade.php
@extends('admin.layouts.admin')
@section('content')


    <!-- Breadcrumb Area -->

    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Դասավանդողներ</li>
            </ol>
        </nav>
    </div>

    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            @can('news_create')
            <a class="btn btn-success" href="{{ route("admin.lessonPrice.create") }}">
                Опубликовано
            </a>
            @endcan
        </div>
    </div>
    <!-- Wrapper -->
    <div class="wrapper wrapper-content blog">
        <div class="container-fluid">
            <div class="row">

                @foreach($lessonPrice as $key => $lessonPrices)
                <div class="col-md-6 col-lg-4">
                    <!-- Ibox -->
                    <div class="ibox bg-boxshadow mb-50">
                        <!-- Content -->
                        <div class="ibox-content blog">

                            <!-- Date -->
                            <div class="blog-date">
                                <table border="1" width="100%">
                                    <tr>
                                        <th>րոպե</th>
                                        <td>{{ $lessonPrices->math ?? '' }}</td>
                                    </tr>
                                    <tr>
                                        <th>Ամիս</th>
                                        <td>{{$lessonPrices->time}}</td>
                                    </tr>
                                    <tr>
                                        <th>Online Անհատական</th>
                                        <td>{{$lessonPrices->onlinePersonal}} դրամ</td>
                                    </tr>
                                    <tr>
                                        <th>Online Խմբակային</th>
                                        <td>{{$lessonPrices->onlineGroup}} դրամ</td>
                                    </tr>
                                    <tr>
                                        <th>offline Անհատական</th>
                                        <td>{{$lessonPrices->offlinePersonal}} դրամ</td>
                                    </tr>
                                    <tr>
                                        <th>offline Խմբակային</th>
                                        <td>{{$lessonPrices->offlineGroup}} դրամ</td>
                                    </tr>
                                </table>
                            </div>




                            <div class="row">
                                <div class="col-md-8">

                                    @can('news_edit')
                                    <button class="btn btn-white btn-xs blog" type="button" onclick="location.href='{{route('admin.lessonPrice.edit',$lessonPrices->id)}}'">Редактировать</button>
                                    @endcan
                                    @can('news_delete')
                                        <form action="{{ route('admin.lessonPrice.destroy', $lessonPrices->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button class="btn  btn-danger btn-xs blog" type="submit">Удалить</button>
                                        </form>
                                    @endcan
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                      @endforeach

            </div>
        </div>
    </div>


@endsection