routes/web.php
<?php

Route::get('/', 'WelcomeController@index')->name('index');
Route::get('/aboutUs', 'WelcomeController@abouts')->name('about');
Route::get('{id?}-and-pricing', 'WelcomeController@service')->name('service');
Route::get('/our-Work', 'WelcomeController@ourworks')->name('our.work');
Route::get('/web/school', 'WelcomeController@school')->name('school.lesson');
Route::get('/lesson-register/{data?}', 'WelcomeController@lessonregister')->name('lesson.register');
Route::post('/register/lesson', 'Lesson_registration_Controller@store')->name('lessonRegister.store');
Route::get('web/lesson', 'WelcomeController@lesson')->name('lesson');
Route::get('special/{data}', 'WelcomeController@special')->name('special');
Route::get('show-{lesson}', 'WelcomeController@lessonshow')->name('lesson.show');

Route::get('/blog/news', 'Blog_Controller@blogitems')->name('blognews');
Route::get('/blog/{id}', 'Blog_Controller@blogid')->name('blogid');
Route::post('/blog/created', 'Blog_Controller@create')->name('blog.created');
Route::get('/contact', 'WelcomeController@contact')->name('contact');
Route::post('/send', 'WelcomeController@send')->name('send');
Route::post('/package', 'WelcomeController@packages')->name('package');
Auth::routes(['register' => false]);
Route::redirect('/home', '/admin');



Route::group([ 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::resource('campetition', 'CampetitionController');
    Route::get('ajaxRequest/{id}', 'CampetitionController@ajaxRequest');
    Route::get('result', 'CampetitionController@result')->name('results');
    Route::get('trashCache', 'CampetitionController@trashCache')->name('trashCache');

});
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/contact', 'ContactController');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');
    Route::resource('slider', 'SliderController');
    Route::resource('about', 'AboutParentController');
    Route::resource('aboutinform', 'AboutInformController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');
    Route::resource('blog', 'BlogController');
    Route::get('blog/chek/slug', 'BlogController@chek')->name('chek.slug');
    Route::resource('service', 'ServiceController');
    Route::resource('service', 'ServiceController');
    Route::get('service/view/{id}', 'ServiceInformateController@view')->name('service_info.view');
    Route::get('service/add/{id}', 'ServiceInformateController@create')->name('service_info.created');
    Route::resource('service_info', 'ServiceInformateController');
    Route::resource('service_Package', 'ServicePackage');
    Route::get('service/Package/{id}', 'ServicePackage@creates')->name('ChildservicesPackage');
    Route::resource('bcomments', 'BlogCommentsController');
    Route::post('bcomments/delete', 'BlogCommentsController@delete')->name('comment.delete');


//    Lesson start


        Route::resource('lesson', 'Lesson\LessonController');
        Route::resource('trainers', 'Lesson\LessonTrainersController');
        Route::resource('lessonPrice', 'Lesson\LessonPriceController');
        Route::resource('special', 'Lesson\LessonSpecialModels');
        Route::resource('specialInform', 'Lesson\LessonSpecialInformateModels');
        Route::get('specialInforms/{data}', 'Lesson\LessonSpecialInformateModels@create')->name('create.special');
        Route::get('packageLesson', 'RegisterPackageController@lesson')->name('package.Lesson');
        Route::get('packageLessons/{id}', 'RegisterPackageController@lessonUpdate')->name('package.Lessons');

        Route::get('packageService', 'RegisterPackageController@service')->name('package.Service');
        Route::get('packageService/{id}', 'RegisterPackageController@serviceUpdate')->name('package.Services');







});

resources/views/admin/service/info/package/create.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">


        <div class="card-body">
            <form action="{{ route("admin.service_Package.store") }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label for="name">Заглавие</label>
                    <input type="text" id="name" name="title" class="form-control" value="" >
                    @if($errors->has('title'))
                        <em class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}" >
                    <label for="description">предложение авторизации пользователя</label>
                    <br>
                    <textarea name="description" class="form-control inputFields ncontent" ></textarea>
                    @if($errors->has('description'))
                        <em class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </em>
                    @endif
                </div>


                <input type="hidden" name="child_id" value="{{$id}}">

                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>

@endsection
@section('js')

    <script>
$(function () {
$("#date").datetime({value: '+1min'});
$("#update_cmd").button();
$("#status").buttonset();
$("#top_fut").buttonset();
$("#lang").buttonset();
$("#catList").buttonset();
});
tinymce.init({
selector: '.ncontent',
menubar: false,
plugins: [
"advlist autolink link image lists charmap print preview hr anchor pagebreak fullscreen",
"searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking spellchecker",
"table contextmenu directionality emoticons paste textcolor responsivefilemanager code"
],
relative_urls: false,
image_advtab: true,
filemanager_title: "Responsive Filemanager",
file_picker_types: 'file image media',
external_filemanager_path: "/admin/filemanager/",
toolbar1: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent blockquote | formatselect removeformat | fullscreen",
toolbar2: "undo redo | cut copy paste pastetext | forecolor backcolor | searchreplace  | responsivefilemanager | image | media | link unlink  | code",
file_picker_callback: function (cb, value, meta) {
var width = window.innerWidth - 30;
var height = window.innerHeight - 60;
if (width > 1800) width = 1800;
if (height > 1200) height = 1200;
if (width > 600) {
var width_reduce = (width - 20) % 138;
width = width - width_reduce + 10;
}
var urltype = 2;
if (meta.filetype == 'image') {
urltype = 1;
}
if (meta.filetype == 'media') {
urltype = 3;
}
let title = "RESPONSIVE FileManager";
if (typeof this.settings.filemanager_title !== "undefined" && this.settings.filemanager_title) {
title = this.settings.filemanager_title;
}
let akey = "key";
if (typeof this.settings.filemanager_access_key !== "undefined" && this.settings.filemanager_access_key) {
akey = this.settings.filemanager_access_key;
}
let sort_by = "";
if (typeof this.settings.filemanager_sort_by !== "undefined" && this.settings.filemanager_sort_by) {
sort_by = "&sort_by=" + this.settings.filemanager_sort_by;
}
let descending = "false";
if (typeof this.settings.filemanager_descending !== "undefined" && this.settings.filemanager_descending) {
descending = this.settings.filemanager_descending;
}
let fldr = "";
if (typeof this.settings.filemanager_subfolder !== "undefined" && this.settings.filemanager_subfolder) {
fldr = "&fldr=" + this.settings.filemanager_subfolder;
}
let crossdomain = "";
if (typeof this.settings.filemanager_crossdomain !== "undefined" && this.settings.filemanager_crossdomain) {
crossdomain = "&crossdomain=1";

// Add handler for a message from ResponsiveFilemanager
if (window.addEventListener) {
window.addEventListener('message', filemanager_onMessage, false);
} else {
window.attachEvent('onmessage', filemanager_onMessage);
}
}
tinymce.activeEditor.windowManager.open({
title: title,
file: this.settings.external_filemanager_path + 'dialog.php?type=' + urltype + '&descending=' + descending + sort_by + fldr + crossdomain + '&lang=' + this.settings.language + '&akey=' + akey,
width: width,
height: height,
resizable: true,
maximizable: true,
inline: 1
}, {
setUrl: function (url) {
cb(url);
}
});
},
});
</script>


@endsection

resources/views/admin/service/info/package/edit.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">


        <div class="card-body">
            <form action="{{ route("admin.service_Package.update",$id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('put')



                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label for="name">Заглавие</label>
                    <input type="text" id="name" name="title" class="form-control" value="{{ old('title', isset($package) ? $package->title : '') }}" >
                    @if($errors->has('title'))
                        <em class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}" >
                    <label for="description">предложение авторизации пользователя</label>
                    <br>
                    <textarea name="description" class="form-control inputFields ncontent" >{{ old('description', isset($package) ? $package->description : '') }}</textarea>
                    @if($errors->has('description'))
                        <em class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </em>
                    @endif
                </div>

                <input type="hidden" name="child_id" value="{{$package->child_id}}">

                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>




@endsection

@section('js')

    <script>
        $(function () {
            $("#date").datetime({value: '+1min'});
            $("#update_cmd").button();
            $("#status").buttonset();
            $("#top_fut").buttonset();
            $("#lang").buttonset();
            $("#catList").buttonset();
        });
        tinymce.init({
            selector: '.ncontent',
            menubar: false,
            plugins: [
                "advlist autolink link image lists charmap print preview hr anchor pagebreak fullscreen",
                "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking spellchecker",
                "table contextmenu directionality emoticons paste textcolor responsivefilemanager code"
            ],
            relative_urls: false,
            image_advtab: true,
            filemanager_title: "Responsive Filemanager",
            file_picker_types: 'file image media',
            external_filemanager_path: "/admin/filemanager/",
            toolbar1: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent blockquote | formatselect removeformat | fullscreen",
            toolbar2: "undo redo | cut copy paste pastetext | forecolor backcolor | searchreplace  | responsivefilemanager | image | media | link unlink  | code",
            file_picker_callback: function (cb, value, meta) {
                var width = window.innerWidth - 30;
                var height = window.innerHeight - 60;
                if (width > 1800) width = 1800;
                if (height > 1200) height = 1200;
                if (width > 600) {
                    var width_reduce = (width - 20) % 138;
                    width = width - width_reduce + 10;
                }
                var urltype = 2;
                if (meta.filetype == 'image') {
                    urltype = 1;
                }
                if (meta.filetype == 'media') {
                    urltype = 3;
                }
                let title = "RESPONSIVE FileManager";
                if (typeof this.settings.filemanager_title !== "undefined" && this.settings.filemanager_title) {
                    title = this.settings.filemanager_title;
                }
                let akey = "key";
                if (typeof this.settings.filemanager_access_key !== "undefined" && this.settings.filemanager_access_key) {
                    akey = this.settings.filemanager_access_key;
                }
                let sort_by = "";
                if (typeof this.settings.filemanager_sort_by !== "undefined" && this.settings.filemanager_sort_by) {
                    sort_by = "&sort_by=" + this.settings.filemanager_sort_by;
                }
                let descending = "false";
                if (typeof this.settings.filemanager_descending !== "undefined" && this.settings.filemanager_descending) {
                    descending = this.settings.filemanager_descending;
                }
                let fldr = "";
                if (typeof this.settings.filemanager_subfolder !== "undefined" && this.settings.filemanager_subfolder) {
                    fldr = "&fldr=" + this.settings.filemanager_subfolder;
                }
                let crossdomain = "";
                if (typeof this.settings.filemanager_crossdomain !== "undefined" && this.settings.filemanager_crossdomain) {
                    crossdomain = "&crossdomain=1";

// Add handler for a message from ResponsiveFilemanager
                    if (window.addEventListener) {
                        window.addEventListener('message', filemanager_onMessage, false);
                    } else {
                        window.attachEvent('onmessage', filemanager_onMessage);
                    }
                }
                tinymce.activeEditor.windowManager.open({
                    title: title,
                    file: this.settings.external_filemanager_path + 'dialog.php?type=' + urltype + '&descending=' + descending + sort_by + fldr + crossdomain + '&lang=' + this.settings.language + '&akey=' + akey,
                    width: width,
                    height: height,
                    resizable: true,
                    maximizable: true,
                    inline: 1
                }, {
                    setUrl: function (url) {
                        cb(url);
                    }
                });
            },
        });
    </script>


@endsection

resources/views/admin/service/info/package/index.blade.php
@extends('admin.layouts.admin')
@section('content')

    <!-- Breadcrumb Area -->

    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Наши услуги</li>
            </ol>
        </nav>
    </div>

    @can('service_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.ChildservicesPackage",$id) }}">
                Опубликовано
            </a>
        </div>
    </div>
    @endcan
    <!-- Wrapper -->
    <div class="wrapper wrapper-content blog">
        <div class="container-fluid">
            <div class="row">

                @foreach($service as $key => $services)
                <div class="col-md-6 col-lg-4">
                    <!-- Ibox -->
                    <div class="ibox bg-boxshadow mb-50">
                        <!-- Content -->
                        <div class="ibox-content blog">
                            <a href="">
                                <h4>{{ $services->title ?? '' }}</h4>
                                <p>{!! $services->description !!}</p>
                            </a>

                            <div class="row">
                                <div class="col-md-8">
                                    <h5 class="blog-tag">Настройка:</h5>
                                    @can('service_edit')
                                        <button class="btn btn-white btn-xs blog" type="button" onclick="location.href='{{route('admin.service_Package.edit',$services->id)}}'">Редактировать</button>
                                    @endcan


                                    @can('service_delete')
                                        <form action="{{ route('admin.service_Package.destroy', $services->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button class="btn  btn-danger btn-xs blog" type="submit">Удалить</button>
                                        </form>
                                    @endcan
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                      @endforeach

            </div>
        </div>
    </div>


@endsection