routes/web.php
<?php

Route::get('/', 'WelcomeController@index')->name('index');
Route::get('/aboutUs', 'WelcomeController@abouts')->name('about');
Route::get('{id?}-and-pricing', 'WelcomeController@service')->name('service');
Route::get('/our-Work', 'WelcomeController@ourworks')->name('our.work');
Route::get('/web/school', 'WelcomeController@school')->name('school.lesson');
Route::get('/lesson-register/{data?}', 'WelcomeController@lessonregister')->name('lesson.register');
Route::post('/register/lesson', 'Lesson_registration_Controller@store')->name('lessonRegister.store');
Route::get('web/lesson', 'WelcomeController@lesson')->name('lesson');
Route::get('special/{data}', 'WelcomeController@special')->name('special');
Route::get('show-{lesson}', 'WelcomeController@lessonshow')->name('lesson.show');

Route::get('/blog/news', 'Blog_Controller@blogitems')->name('blognews');
Route::get('/blog/{id}', 'Blog_Controller@blogid')->name('blogid');
Route::post('/blog/created', 'Blog_Controller@create')->name('blog.created');
Route::get('/contact', 'WelcomeController@contact')->name('contact');
Route::post('/send', 'WelcomeController@send')->name('send');
Route::post('/package', 'WelcomeController@packages')->name('package');
Auth::routes(['register' => false]);
Route::redirect('/home', '/admin');



Route::group([ 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::resource('campetition', 'CampetitionController');
    Route::get('ajaxRequest/{id}', 'CampetitionController@ajaxRequest');
    Route::get('result', 'CampetitionController@result')->name('results');
    Route::get('trashCache', 'CampetitionController@trashCache')->name('trashCache');

});
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/contact', 'ContactController');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');
    Route::resource('slider', 'SliderController');
    Route::resource('about', 'AboutParentController');
    Route::resource('aboutinform', 'AboutInformController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');
    Route::resource('blog', 'BlogController');
    Route::get('blog/chek/slug', 'BlogController@chek')->name('chek.slug');
    Route::resource('service', 'ServiceController');
    Route::resource('service', 'ServiceController');
    Route::get('service/view/{id}', 'ServiceInformateController@view')->name('service_info.view');
    Route::get('service/add/{id}', 'ServiceInformateController@create')->name('service_info.created');
    Route::resource('service_info', 'ServiceInformateController');
    Route::resource('service_Package', 'ServicePackage');
    Route::get('service/Package/{id}', 'ServicePackage@creates')->name('ChildservicesPackage');
    Route::resource('bcomments', 'BlogCommentsController');
    Route::post('bcomments/delete', 'BlogCommentsController@delete')->name('comment.delete');


//    Lesson start


        Route::resource('lesson', 'Lesson\LessonController');
        Route::resource('trainers', 'Lesson\LessonTrainersController');
        Route::resource('lessonPrice', 'Lesson\LessonPriceController');
        Route::resource('special', 'Lesson\LessonSpecialModels');
        Route::resource('specialInform', 'Lesson\LessonSpecialInformateModels');
        Route::get('specialInforms/{data}', 'Lesson\LessonSpecialInformateModels@create')->name('create.special');
        Route::get('packageLesson', 'RegisterPackageController@lesson')->name('package.Lesson');
        Route::get('packageLessons/{id}', 'RegisterPackageController@lessonUpdate')->name('package.Lessons');

        Route::get('packageService', 'RegisterPackageController@service')->name('package.Service');
        Route::get('packageService/{id}', 'RegisterPackageController@serviceUpdate')->name('package.Services');







});

resources/views/admin/Lesson/special/info/create.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">


        <div class="card-body">
            <form action="{{ route("admin.specialInform.store") }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label for="name">Заглавие</label>
                    <input type="text" id="name" name="title" class="form-control" value="" required>
                    @if($errors->has('title'))
                        <em class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </em>
                    @endif
                </div>


                <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                    <label for="description">description: </label>
                    <textarea id="name" name="description" class="form-control"  required></textarea>
                    @if($errors->has('description'))
                        <em class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </em>
                    @endif
                </div>
                <input type="hidden" name="parent_id" value="{{$id}}">

                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/Lesson/special/info/edit.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">


        <div class="card-body">
            <form action="{{ route("admin.specialInform.update",$id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('put')

                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label for="name">Заглавие:</label>
                    <input type="text" id="name" name="title" class="form-control" value="{{ old('title', isset($specialInform) ? $specialInform->title : '') }}" required>
                    @if($errors->has('title'))
                        <em class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </em>
                    @endif
                </div>


                <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                    <label for="description">description: </label>
                  @if($errors->has('description'))
                        <em class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </em>
                    @endif
                    <textarea id="name" name="description" class="form-control"  required>{{ old('description', isset($specialInform) ? $specialInform->description : '') }}</textarea>
                </div>
                <input type="hidden" name="parent_id" value="{{$specialInform->parent_id}}">

                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>




@endsection

resources/views/admin/Lesson/special/info/index.blade.php
@extends('admin.layouts.admin')
@section('content')


    <!-- Breadcrumb Area -->

    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Наши услуги</li>
            </ol>
        </nav>
    </div>
    @can('service_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{route('admin.create.special',$id)}}">
                Опубликовано
            </a>
        </div>
    </div>
    @endcan
    <!-- Wrapper -->
    <div class="wrapper wrapper-content blog">
        <div class="container-fluid">
            <div class="row">

                @foreach($specialInform as $key => $specialInforms)
                <div class="col-md-6 col-lg-4">
                    <!-- Ibox -->
                    <div class="ibox bg-boxshadow mb-50">
                        <!-- Content -->
                        <div class="ibox-content blog">
                            <a href="">
                                <h4>{{ $specialInforms->title ?? '' }}</h4>
                            </a>
                            <!-- Date -->
                            <div class="blog-date">
                                <p><strong>{{$specialInforms->description}}</strong> <span><i class="fa fa-clock-o"></i></span>
                                </p>
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    <h5 class="blog-tag">Настройка:</h5>
                                    @can('service_edit')
                                        <button class="btn btn-white btn-xs blog" type="button" onclick="location.href='{{route('admin.specialInform.edit',$specialInforms->id)}}'">Редактировать</button>
                                    @endcan


                                    @can('service_delete')
                                        <form action="{{ route('admin.specialInform.destroy', $specialInforms->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button class="btn  btn-danger btn-xs blog" type="submit">Удалить</button>
                                        </form>
                                    @endcan
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                      @endforeach

            </div>
        </div>
    </div>


@endsection

resources/views/admin/Lesson/special/info/show.blade.php
@extends('admin.layouts.admin')
@section('content')

    <div class="card">
        <div class="card-header">
            Наши услуги
        </div>
        <h1 align="center">    {{ $service->title }}</h1>
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <tbody>

                <tr>
                    <th>
                        Заглавие
                    </th>
                    <td>
                        {{ $service->title }}
                    </td>
                </tr>
                <tr>
                    <th>
                        Описание
                    </th>
                    <td>
                        {{ $service->price }}
                    </td>
                </tr>
                @foreach($package as $packagess)
                <tr>
                    <th>
                        предложение авторизации пользователя
                    </th>
                    <td>
                        {{ $packagess->title }}
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>


        </div>
    </div>

@endsection